// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://aguicius.com
// Generated: 2026-06-18T16:54:08.199Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary';
export type ColorHex  = '#6c6d74' | '#ffffff' | '#2d2e33' | '#b4b5ba' | '#e5e5e7' | '#242427' | '#808080' | '#414141' | '#850064';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Montserrat';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '700';

export type SpacingToken = '5px' | '40px' | '70px' | '140px' | '180px' | '200px';

export type RadiusToken = '50px';

export type DurationToken = '100ms' | '200ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
